### ISSUE TITLE
Why is there no arg of cutoff for autocontrast at this line?

### ISSUE THREAD

**Issue by CoinCheung** [DeepVoltaire/AutoAugment#22]
https://github.com/DeepVoltaire/AutoAugment/blob/17d718251f25c0d9413bf30f91b523907924f33a/autoaugment.py#L218

Hi, 

I notice that for `autocontrast`, the magnitude is not used, and for `ImageOps.autocontrast`, there is an args named `cutoff`, which controls the degree of contrast.  If we set `cutoff=0`, the original image would be returned by this function. Does this mean that the `ImageOps.autocontrast` is not used at all in both the auto-ml search phase and the verification phase(experiments on imagenet dataset) ?

**Comment by DeepVoltaire** [comment]
In the paper they use autocontrast to "Maximize the image contrast, by making the darkest pixel
black and lightest pixel white.". autocontrast() does only return the original image when cutoff=0 when the image has pixel values of 0 and 255. If not, the darkest pixel is mapped to 0, the lightest pixel to white and everything in between is remapped. See the documentation of autocontrast() https://pillow.readthedocs.io/en/stable/reference/ImageOps.html:

"Maximize (normalize) image contrast. This function calculates a histogram of the input image (or mask region), removes cutoff percent of the lightest and darkest pixels from the histogram, and remaps the image so that the darkest pixel becomes black (0), and the lightest becomes white (255)."
